services:
# Organizr - Unified Frontend
  organizr:
    <<: *common-keys-apps
    image: organizr/organizr
    container_name: organizr
    profiles: ["infra", "all"]
#    ports:
#      - "$ORGANIZR_PORT:80"
    volumes:
      - $DOCKERDIR/organizr:/config
    environment:
      <<: *default-tz-puid-pgid
      FPM: true
      BRANCH: v2-master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr-rtr.entrypoints=https"
      - "traefik.http.routers.organizr-rtr.rule=Host(`organizr.$DOMAINNAME`)"
      - "traefik.http.routers.organizr-rtr.middlewares=chain-oauth@file"
      # - "traefik.http.routers.organizr-rtr.rule=Host(`$DOMAINNAME`) || Host(`www.$DOMAINNAME`)"
      # - "traefik.http.routers.organizr-rtr.middlewares=organizr-redirect@docker,chain-oauth@file"
      # - "traefik.http.middlewares.organizr-redirect.redirectregex.regex=^https?://$DOMAINNAME/(.*)"
      # - "traefik.http.middlewares.organizr-redirect.redirectregex.replacement=https://www.$DOMAINNAME/$${1}"
      # - "traefik.http.middlewares.organizr-redirect.redirectregex.permanent=true"
      - "traefik.http.routers.organizr-rtr.service=organizr-svc"
      - "traefik.http.services.organizr-svc.loadbalancer.server.port=80"