services:
# Postgres - Database for TeslaMate
  postgres:
    image: postgres:15
    container_name: postgres
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["infra", "all"]
    volumes:
      - $DOCKERDIR/postgres:/var/lib/postgresql/data
    environment:
      <<: *default-tz-puid-pgid
      POSTGRES_DB__FILE: /run/secrets/teslamate_db_name
      POSTGRES_USER__FILE: /run/secrets/teslamate_db_user
      POSTGRES_PASSWORD__FILE: /run/secrets/teslamate_db_password
    secrets:
      - teslamate_db_name
      - teslamate_db_user
      - teslamate_db_password
#      POSTGRES_MULTIPLE_DATABASES: statping-{{ statping_db_pass }},teslamate-{{ teslamate_db_pass }}