services:
# Bazarr - Subtitle Management
  bazarr:
    <<: *common-keys-apps
    image: linuxserver/bazarr
    container_name: bazarr
    profiles: ["media", "all"]
    ports:
      - "$BAZARR_PORT:6767"
    volumes:
      - $DOCKERDIR/bazarr:/config
      - $USERDIR/media/movies:/movies
      - $USERDIR/media/tvshows:/tv
      - $USERDIR/media/kidsmovies:/kidsmovies
    environment:
      <<: *default-tz-puid-pgid
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth Bypass
      - "traefik.http.routers.bazarr-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.bazarr-rtr-bypass.rule=Host(`bazarr2.$DOMAINNAME`) && (Header(`X-Api-Key`, `$BAZARR_API`) || Query(`apikey`, `$BAZARR_API`))"
      - "traefik.http.routers.bazarr-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.bazarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.bazarr-rtr.rule=Host(`bazarr2.$DOMAINNAME`)"
      - "traefik.http.routers.bazarr-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.bazarr-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.bazarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.bazarr-rtr.service=bazarr-svc"
      - "traefik.http.routers.bazarr-rtr-bypass.service=bazarr-svc"
      - "traefik.http.services.bazarr-svc.loadbalancer.server.port=6767"