services:
# Firefox - Web Broswer
  firefox:
    <<: *common-keys-apps
    image: jlesage/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined # October 15, 2020 https://github.com/jlesage/docker-firefox/blob/master/README.md#allowing-the-membarrier-system-call
    profiles: ["ff"]
    # ports:
    #   - "$FIREFOX_PORT:5800"
    volumes:
      - $DOCKERDIR/firefox:/config
      - $DOWNLOAD_DIR:/data/downloads
      - /dev/shm:/dev/shm
    environment:
      <<: *default-tz-puid-pgid
      UMASK: 002
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1920
      DISPLAY_HEIGHT: 1080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefox-rtr.entrypoints=websecure"
      - "traefik.http.routers.firefox-rtr.rule=Host(`firefox2.$DOMAINNAME`)"
      - "traefik.http.routers.firefox-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.firefox-rtr.service=firefox-svc"
      - "traefik.http.services.firefox-svc.loadbalancer.server.port=5800"