services:
# Torrent Proxy for Cloudflare
  flaresolverr:
    <<: *common-keys-apps
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    profiles: ["media", "all"]
    environment:
      <<: *default-tz-puid-pgid
      #LOG_LEVEL: ${LOG_LEVEL:-info}
      #LOG_HTML: ${LOG_HTML:-false}
      CAPTCHA_SOLVER: ${CAPTCHA_SOLVER:-none}
    # ports:
    #   - "${PORT:-8191}:8191"