services:
# NetbootXYZ PXE Boot Service
  netbootxyz:
    <<: *common-keys-core
    image: lscr.io/linuxserver/netbootxyz:latest
    container_name: netbootxyz
    profiles: ["infra","all"]
    environment:
      <<: *default-tz-puid-pgid
#      MENU_VERSION: 1.9.9
      PORT_RANGE: 30000:30010
      SUBFOLDER: /
    volumes:
      - $DOCKERDIR/netbootxyz/config:/config
      - $DOCKERDIR/netbootxyz/assets:/assets #optional
    ports:
      - 3000:3000
      - 69:69/udp
#      - 8080:80 #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.netbootxyz-rtr.entrypoints=https"
      - "traefik.http.routers.netbootxyz-rtr.rule=Host(`netbootxyz.$DOMAINNAME`)"
      - "traefik.http.routers.netbootxyz-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.vnetbootxyz-rtr.service=netbootxyz-svc"
      - "traefik.http.services.netbootxyz-svc.loadbalancer.server.port=3000"