services:
# NZBHydra2 - NZB meta search
  hydra:
    <<: *common-keys-apps
    image: linuxserver/nzbhydra2
    container_name: hydra
    profiles: ["media", "all"]
#    ports:
#      - "$NZBHYDRA_PORT:5076"
    volumes:
      - $DOCKERDIR/hydra2:/config
      - $DOWNLOAD_DIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.hydra-rtr.entrypoints=websecure"
     - "traefik.http.routers.hydra-rtr.rule=Host(`hydra2.$DOMAINNAME`)"
     - "traefik.http.routers.hydra-rtr.middlewares=chain-oauth@file"
     - "traefik.http.routers.hydra-rtr.service=hydra-svc"
     - "traefik.http.services.hydra-svc.loadbalancer.server.port=5076"