services:
#TESLAMATE - TeslaMate Logging for Tesla        
  teslamate:
    <<: *common-keys-apps
    image: teslamate/teslamate
    container_name: teslamate
    profiles: ["infra", "all"]
    depends_on:
      - postgres
    environment:
      <<: *default-tz-puid-pgid
      ENCRYPTION_KEY: $TESLAMATE_EK
      DATABASE_USER: $TESLAMATE_DB_USER
      DATABASE_PASS: $TESLAMATE_DB_PASS
      DATABASE_NAME: $TESLAMATE_DB
#      ENCRYPTION_KEY__FILE: /run/secrets/teslamate_ek
#      DATABASE_USER__FILE: /run/secrets/teslamate_db_user
#      DATABASE_PASS__FILE: /run/secrets/teslamate_db_password
#      DATABASE_NAME__FILE: /run/secrets/teslamate_db_name
      DATABASE_HOST: postgres
      MQTT_HOST: mosquitto
      VIRTUAL_HOST: teslamate.$DOMAINNAME
      CHECK_ORIGIN: "true"
#    secrets:
#      - teslamate_db_name
#      - teslamate_db_user
#      - teslamate_db_password
#      - teslamate_ek
#    ports:
#      - "$TM_PORT:4000"
    volumes:
      - $DOCKERDIR/teslamate/import:/opt/app/import
    cap_drop:
      - all
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teslamate-rtr.entrypoints=https"
      - "traefik.http.routers.teslamate-rtr.rule=Host(`teslamate.$DOMAINNAME`)"
      - "traefik.http.routers.teslamate-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.teslamate-rtr.service=teslamate-svc"
      - "traefik.http.services.teslamate-svc.loadbalancer.server.port=4000"

# Grafana - TeslaMate
  grafanatm:
    <<: *common-keys-apps
    image: teslamate/grafana
    container_name: grafanatm
    profiles: ["infra", "all"]
    environment:
      <<: *default-tz-puid-pgid
      DATABASE_HOST: postgres
      GRAFANA_PASSWD__FILE: /run/secrets/grafana_pw
#      GF_SECURITY_ADMIN_USER__FILE: /run/secrets/grafana_admin_user
#      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_admin_pw
      GF_AUTH_ANONYMOUS_ENABLED: "false"
      GF_AUTH_BASIC_ENABLED: "true"
      GF_SERVER_ROOT_URL: "https://grafanatm.$DOMAINNAME"
      GF_SERVER_SERVE_FROM_SUB_PATH: "false"
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: "X-WEBAUTH-USER"
      GF_AUTH_PROXY_HEADER_PROPERTY: "username"
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_PROXY_LDAP_SYNC_TTL: 60
      GF_AUTH_PROXY_WHITELIST: "$IPWHITELIST"
      GF_AUTH_PROXY_HEADERS: "Email:X-User-Email, Name:X-User-Name"
      DATABASE_NAME__FILE: /run/secrets/teslamate_db_name
      DATABASE_USER__FILE: /run/secrets/teslamate_db_user
      DATABASE_PASS__FILE: /run/secrets/teslamate_db_password
    secrets:
      - teslamate_db_name
      - teslamate_db_user
      - teslamate_db_password
#      - grafana_admin_user
      - grafana_pw
#      - grafana_admin_pw
    volumes:
      - $DOCKERDIR/grafanatm/grafana.ini:/etc/grafana/grafana.ini
      - teslamate-grafana-data:/var/lib/grafana
#    ports:
#      - "$GRAFANATM_PORT:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafanatm-rtr.entrypoints=https"
      - "traefik.http.routers.grafanatm-rtr.rule=Host(`grafanatm.$DOMAINNAME`)"
      - "traefik.http.routers.grafanatm-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.grafanatm-rtr.service=grafanatm-svc"
      - "traefik.http.services.grafanatm-svc.loadbalancer.server.port=3000"

volumes:
  teslamate-grafana-data: