########################### THIS COMPOSE FILE
# - Home Server (plex) - Ubuntu Server 22.04
# - Docker version 26.1.3, build 8e96db1
# - Docker Compose version v2.27.0

########################### NETWORKS
# You may customize the network subnets (192.168.x.0/24) below as you please.
networks:
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
  t3_proxy:
    name: t3_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24

########################### SECRETS
secrets:
  basic_auth_credentials:
    file: $DOCKERDIR/secrets/htpasswd
  cf_dns_api_token:
    file: $DOCKERDIR/secrets/cf_dns_api_token
  authelia_jwt_secret:
    file: $DOCKERDIR/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: $DOCKERDIR/secrets/authelia_session_secret
  # authelia_storage_mysql_password:
  #   file: $DOCKERDIR/secrets/authelia_storage_mysql_password
  # authelia_notifier_smtp_password:
  #   file: $DOCKERDIR/secrets/authelia_notifier_smtp_password
  # authelia_duo_api_secret_key:
  #   file: $DOCKERDIR/secrets/authelia_duo_api_secret_key
  authelia_storage_encryption_key:
    file: $DOCKERDIR/secrets/authelia_storage_encryption_key
  plex_claim:
    file: $DOCKERDIR/secrets/plex_claim
  plex_token:
    file: $DOCKERDIR/secrets/plex_token
  mysql_root_password:
    file: $DOCKERDIR/secrets/mysql_root_password
  # teslamate_db_name:
  #   file: $DOCKERDIR/secrets/teslamate_db_name
  # teslamate_db_user:
  #   file: $DOCKERDIR/secrets/teslamate_db_user
  # teslamate_db_password:
  #   file: $DOCKERDIR/secrets/teslamate_db_password
  # teslamate_ek:
  #   file: $DOCKERDIR/secrets/teslamate_ek
  transmission_rpc_username:
    file: $DOCKERDIR/secrets/transmission_rpc_username
  transmission_rpc_password:
    file: $DOCKERDIR/secrets/transmission_rpc_password
  pia_username:
    file: $DOCKERDIR/secrets/pia_username
  pia_password:
    file: $DOCKERDIR/secrets/pia_password
  htpasswd:
    file: $DOCKERDIR/secrets/htpasswd
  http_password:
    file: $DOCKERDIR/secrets/http_password
  http_username:
    file: $DOCKERDIR/secrets/http_username
  # nc_db_name:
  #   file: $DOCKERDIR/secrets/nc_db_name
  # nc_db_user:
  #   file: $DOCKERDIR/secrets/nc_db_user
  # nc_db_password:
  #   file: $DOCKERDIR/secrets/nc_db_password
  # nc_admin_user:
  #   file: $DOCKERDIR/secrets/nc_admin_user
  # nc_admin_password:
  #   file: $DOCKERDIR/secrets/nc_admin_password
  # grafana_admin_user:
  #   file: $DOCKERDIR/secrets/grafana_admin_user
  # grafana_pw:
  #   file: $DOCKERDIR/secrets/grafana_pw
  # grafana_admin_pw:
  #   file: $DOCKERDIR/secrets/grafana_admin_pw
  cf_email:
    file: $DOCKERDIR/secrets/cf_email
  cf_api_key:
    file: $DOCKERDIR/secrets/cf_api_key
  traefik_forward_auth:
    file: $DOCKERDIR/secrets/traefik_forward_auth
  guac_db_name:
    file: $DOCKERDIR/secrets/guac_db_name
  guac_mysql_user:
    file: $DOCKERDIR/secrets/guac_mysql_user
  guac_mysql_password:
    file: $DOCKERDIR/secrets/guac_mysql_password
  peerport:
    file: $DOCKERDIR/pia/pia-shared/port.dat
  github_token:
    file: $DOCKERDIR/secrets/github_token
  trakt_clientid:
    file: $DOCKERDIR/secrets/trakt_clientid
  trakt_clientsecret:
    file: $DOCKERDIR/secrets/trakt_clientsecret
  trakt_pin:
    file: $DOCKERDIR/secrets/trakt_pin
  glances_password:
    file: $DOCKERDIR/secrets/glances_password
  glances_pass:
    file: $DOCKERDIR/secrets/glances_pass    
  portainer_key:
    file: $DOCKERDIR/secrets/portainer_key
  radarr_api:
    file: $DOCKERDIR/secrets/radarr_api_key
  sonarr_api:
    file: $DOCKERDIR/secrets/sonarr_api_key
  lidarr_api:
    file: $DOCKERDIR/secrets/lidarr_api_key
  bazarr_api:
    file: $DOCKERDIR/secrets/bazarr_api_key
  mylar_api:
    file: $DOCKERDIR/secrets/mylar_api_key
  readarr_api:
    file: $DOCKERDIR/secrets/readarr_api_key
  prowlarr_api:
    file: $DOCKERDIR/secrets/prowlarr_api_key
  tautulli_api:
    file: $DOCKERDIR/secrets/tautulli_api_key
  sabnzbd_api:
    file: $DOCKERDIR/secrets/sabnzbd_api_key
  ombi_api:
    file: $DOCKERDIR/secrets/ombi_api_key
  omdb_api:
    file: $DOCKERDIR/secrets/omdb_api_key
  tmdb_api:
    file: $DOCKERDIR/secrets/tmdb_api_key
  mdblist_api:
    file: $DOCKERDIR/secrets/mdblist_api_key
  hpusername:
    file: $DOCKERDIR/secrets/hpusername
  hppassword:
    file: $DOCKERDIR/secrets/hppassword

include:
  ########################### SERVICES
  # HOSTNAME=plex - defined in .env

  # CORE
  - compose/$HOSTNAME/traefik.yml
  - compose/$HOSTNAME/socket-proxy.yml
  - compose/$HOSTNAME/oauth.yml
  - compose/$HOSTNAME/authelia.yml
  - compose/$HOSTNAME/portainer.yml
  - compose/$HOSTNAME/dockge.yml
  # SECURITY
  - compose/$HOSTNAME/crowdsec.yml
  - compose/$HOSTNAME/traefik-bouncer.yml
  # FRONTEND
  # - compose/$HOSTNAME/autoindex.yml
  - compose/$HOSTNAME/homepage.yml
  - compose/$HOSTNAME/phpmyadmin.yml
  # - compose/$HOSTNAME/sitespeed.yml
  - compose/$HOSTNAME/whoami.yml
  # DOWNLOADERS
  # - compose/$HOSTNAME/jdownloader.yml
  - compose/$HOSTNAME/qbittorrent.yml
  - compose/$HOSTNAME/sabnzbd.yml
  # PVRS
  - compose/$HOSTNAME/sonarr.yml
  - compose/$HOSTNAME/radarr.yml
  - compose/$HOSTNAME/lidarr.yml
  # COMPLEMENTARY APPS
  - compose/$HOSTNAME/prowlarr.yml
  - compose/$HOSTNAME/notifiarr.yml
  - compose/$HOSTNAME/bazarr.yml
  # - compose/$HOSTNAME/picard.yml
  # MONITORING
  # - compose/$HOSTNAME/grafana.yml
  # - compose/$HOSTNAME/uptime-kuma.yml
  - compose/$HOSTNAME/dozzle.yml
  # - compose/$HOSTNAME/scrutiny.yml
  # - compose/$HOSTNAME/radarr-exporter.yml
  # - compose/$HOSTNAME/sonarr-exporter.yml
  # - compose/$HOSTNAME/lidarr-exporter.yml
  # - compose/$HOSTNAME/prowlarr-exporter.yml
  # - compose/$HOSTNAME/sabnzbd-exporter.yml
  - compose/$HOSTNAME/node-exporter.yml
  # ADMIN
  - compose/$HOSTNAME/guacamole.yml
  - compose/$HOSTNAME/kasm.yml
  - compose/$HOSTNAME/it-tools.yml
  # UTILITIES
  - compose/$HOSTNAME/firefox.yml
  # FILE MANAGEMENT
  - compose/$HOSTNAME/vscode.yml
  # NETWORK
  - compose/$HOSTNAME/gluetun.yml
  # MAINTENANCE
  - compose/$HOSTNAME/docker-gc.yml
  - compose/$HOSTNAME/deunhealth.yml