http:
  routers:  
    rpizwtheater-rtr:
      rule: Host(`rpizwtheater.{{env "DOMAINNAME"}}`)
      service: rpizwtheater-svc
      priority: 1000
      tls:
        certresolver: dns-cloudflare
      entryPoints:
        - websecure
      middlewares:
        - chain-oauth
  
    rpizwpoolspeaker-rtr:
      rule: Host(`rpizwpool.{{env "DOMAINNAME"}}`)
      service: rpizwpool-svc
      priority: 1000
      tls:
        certresolver: dns-cloudflare
      entryPoints:
        - websecure
      middlewares:
        - chain-oauth

    hdhomerun-rtr:
      rule: Host(`hdhomerun.{{env "DOMAINNAME"}}`)
      service: hdhomerun-svc
      priority: 1000
      tls:
        certresolver: dns-cloudflare
      entryPoints:
        - websecure
      middlewares:
        - chain-oauth

    batocerapi5-rtr:
      rule: Host(`batocerapi5.{{env "DOMAINNAME"}}`)
      service: batocerapi5-svc
      priority: 1000
      tls:
        certresolver: dns-cloudflare
      entryPoints:
        - websecure
      middlewares:
        - chain-oauth

    batocerapi4b-rtr:
      rule: Host(`batocerapi4b.{{env "DOMAINNAME"}}`)
      service: batocerapi4b-svc
      priority: 1000
      tls:
        certresolver: dns-cloudflare
      entryPoints:
        - websecure
      middlewares:
        - chain-oauth