services:
# Youtube Downloader
  metube:
    <<: *common-keys-apps 
    image: ghcr.io/alexta69/metube
    container_name: metube
    profiles: ["media", "all"]
    ports:
      - "$METUBE_PORT:8081"
    volumes:
      - $DOWNLOAD_DIR:/downloads
    environment:
      <<: *default-tz-puid-pgid
      DEFAULT_THEME: dark
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.metube-rtr.entrypoints=websecure"
      - "traefik.http.routers.metube-rtr.rule=Host(`metube.$DOMAINNAME`)"
      - "traefik.http.routers.metube-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.metube-rtr.service=metube-svc"
      - "traefik.http.services.metube-svc.loadbalancer.server.port=8081"