services:
#Notifiarr
  notifiarr:
    <<: *common-keys-apps
    image: golift/notifiarr
    container_name: notifiarr
    hostname: notifiarr
    profiles: ["media", "all"]
#    privileged: true
#    ports:
#      - "5454:5454"
    volumes:
      - $DOCKERDIR/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    environment:
      <<: *default-tz-puid-pgid
##      DN_UI_PASSWORD: $HTTP_PASSWORD
      DN_API_KEY: $NOTIFIARR_API
      DN_LIDARR_0_NAME: Lidarr.$DOMAINNAME
      DN_LIDARR_0_URL: http://lidarr:8686/lidarr
      DN_LIDARR_0_API_KEY: $LIDARR_API
      DN_PROWLARR_0_NAME: Prowlarr.$DOMAINNAME
      DN_PROWLARR_0_URL: http://prowlarr:9696
      DN_PROWLARR_0_API_KEY: $PROWLARR_API
#      DN_PROWLARR_0_USERNAME_FILE: /run/secrets/http_username #$HTTP_USERNAME
#      DN_PROWLARR_0_PASSWORD_FILE: /run/secrets/http_password #$HTTP_PASSWORD
      DN_RADARR_0_NAME: Radarr.$DOMAINNAME
      DN_RADARR_0_URL: http://radarr:7878/radarr
      DN_RADARR_0_API_KEY: $RADARR_API
      DN_READARR_0_NAME: Readarr.$DOMAINNAME
      DN_READARR_0_URL: http://readarr:8787
      DN_READARR_0_API_KEY: $READARR_API
      DN_SONARR_0_NAME: Sonarr.$DOMAINNAME
      DN_SONARR_0_URL: http://sonarr:8989/sonarr
      DN_SONARR_0_API_KEY: $SONARR_API
      DN_SABNZBD_0_NAME: Sabnzbd.$DOMAINNAME
      DN_SABNZBD_0_URL: https://sabnzbd:8080
      DN_SABNZBD_0_API_KEY: $SABNZBD_API
      DN_LIDARR_1_NAME: Lidarr2.$DOMAINNAME
      DN_LIDARR_1_URL: https://lidarr2.$DOMAINNAME/lidarr
      DN_LIDARR_1_API_KEY: $LIDARR_API
      DN_PROWLARR_1_NAME: Prowlarr2.$DOMAINNAME
      DN_PROWLARR_1_URL: https://prowlarr2.$DOMAINNAME
      DN_PROWLARR_1_API_KEY: $PROWLARR_API
#      DN_PROWLAR_1_USERNAME_FILE: /run/secrets/http_username #$HTTP_USERNAME
#      DN_PROWLAR_1_PASSWORD_FILE: /run/secrets/http_password #$HTTP_PASSWORD
      DN_RADARR_1_NAME: Radarr2.$DOMAINNAME
      DN_RADARR_1_URL: https://radarr2.$DOMAINNAME/radarr
      DN_RADARR_1_API_KEY: $RADARR_API
      DN_SONARR_1_NAME: Sonarr2.$DOMAINNAME
      DN_SONARR_1_URL: https://sonarr2.$DOMAINNAME/sonarr
      DN_SONARR_1_API_KEY: $SONARR_API
      DN_SABNZBD_1_NAME: Sabnzbd2.$DOMAINNAME
      DN_SABNZBD_1_URL: https://sabnzbd2.$DOMAINNAME
      DN_SABNZBD_1_API_KEY: $SABNZBD_API
      DN_LIDARR_2_NAME: Lidarr.$DOMAINNAME2
      DN_LIDARR_2_URL: https://lidarr.$DOMAINNAME2/lidarr
      DN_LIDARR_2_API_KEY: $LIDARR_API
      DN_PROWLARR_2_NAME: Prowlarr.$DOMAINNAME2
      DN_PROWLARR_2_URL: https://prowlarr.$DOMAINNAME2
      DN_PROWLARR_2_API_KEY: $PROWLARR_API
#      DN_PROWLAR_2_USERNAME_FILE: /run/secrets/http_username #$HTTP_USERNAME
#      DN_PROWLAR_2_PASSWORD_FILE: /run/secrets/http_password #$HTTP_PASSWORD
      DN_RADARR_2_NAME: Radarr.$DOMAINNAME2
      DN_RADARR_2_URL: https://radarr.$DOMAINNAME2/radarr
      DN_RADARR_2_API_KEY: $RADARR_API
      DN_SONARR_2_NAME: Sonarr.$DOMAINNAME2
      DN_SONARR_2_URL: https://sonarr.$DOMAINNAME2/sonarr
      DN_SONARR_2_API_KEY: $SONARR_API
      DN_SABNZBD_2_NAME: Sabnzbd.$DOMAINNAME2
      DN_SABNZBD_2_URL: https://sabnzbd.$DOMAINNAME2
      DN_SABNZBD_2_API_KEY: $SABNZBD_API
      DN_PLEX_URL: https://plex.$DOMAINNAME
#      DN_PLEX_TOKEN_FILE: /run/secrets/plex_token #$PLEX_TOKEN
      DN_TAUTULLI_NAME: Tautulli.$DOMAINNAME
      DN_TAUTULLI_URL: http://tautulli:8181
      DN_TAUTULLI_API_KEY: $TAUTULLI_API
#      HTTP_USERNAME_FILE: /run/secrets/http_username
#      HTTP_PASSWORD_FILE: /run/secrets/http_password
#      PLEX_TOKEN_FILE: /run/secrets/plex_token
    secrets:
      - http_username
      - http_password
      - plex_token
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.notifiarr-rtr.entrypoints=https"
      - "traefik.http.routers.notifiarr-rtr.priority=99"
      - "traefik.http.routers.notifiarr-rtr.rule=Host(`notifiarr.$DOMAINNAME`)"
      - "traefik.http.routers.notifiarr-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.notifiarr-rtr.service=notifiarr-svc"
      - "traefik.http.services.notifiarr-svc.loadbalancer.server.port=5454"
      # API ROUTER - Allow access to API without auth for 3rd party app access
      - "traefik.http.routers.notifiarr-api-rtr.entrypoints=https"
      - "traefik.http.routers.notifiarr-api-rtr.priority=100"
      - "traefik.http.routers.notifiarr-api-rtr.rule=Host(`notifiarr.$DOMAINNAME`) && (Headers(`X-Api-Key`, `$NOTIFIARR_API`) || Query(`apikey=$NOTIFIARR_API`))"
      - "traefik.http.routers.notifiarr-api-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.notifiarr-api-rtr.service=notifiarr-svc"