services:
# Tautulli - Plex statistics and monitoring
  tautulli:
    <<: *common-keys-apps
    image: linuxserver/tautulli
    container_name: tautulli
    profiles: ["media", "all"]
    ports:
      - "$TAUTULLI_PORT:8181"
    volumes:
      - $DOCKERDIR/tautulli/config:/config
      - $DOCKERDIR/tautulli/logs:/logs:ro
    environment:
      <<: *default-tz-puid-pgid
    depends_on:
      - plex
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli-rtr.entrypoints=websecure"
      - "traefik.http.routers.tautulli-rtr.priority=99"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.$DOMAINNAME`)"
      - "traefik.http.routers.tautulli-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
      ## API Oauth Bypass
      - "traefik.http.routers.tautulli-api-rtr.entrypoints=websecure"
      - "traefik.http.routers.tautulli-api-rtr.rule=Host(`tautulli.${DOMAINNAME}`) && (Header(`X-Api-Key`, `${TAUTULLI_DEVICE_KEY1}`) || Query(`apikey`, `${TAUTULLI_DEVICE_KEY1}`))"
      
      - "traefik.http.routers.tautulli-api2-rtr.rule=Host(`tautulli.${DOMAINNAME}`) && (Header(`X-Api-Key`, `${TAUTULLI_DEVICE_KEY2}`) || Query(`apikey`, `${TAUTULLI_DEVICE_KEY2}`))"
      - "traefik.http.routers.tautulli-api3-rtr.rule=Host(`tautulli.${DOMAINNAME}`) && (Header(`X-Api-Key`, `${TAUTULLI_API}`) || Query(`apikey`, `${TAUTULLI_API}`))"
      - "traefik.http.routers.tautulli-api-rtr.priority=100"
      - "traefik.http.routers.tautulli-api2-rtr.priority=101"
      - "traefik.http.routers.tautulli-api3-rtr.priority=102"
      - "traefik.http.routers.tautulli-api-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.tautulli-api-rtr.service=tautulli-svc"