services:
# phpMyAdmin - Database management
  phpmyadmin:
    <<: *common-keys-apps
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - default
      - t3_proxy
    security_opt:
      - no-new-privileges:true
    profiles: ["infra", "all"]    
    ports:
      - "$PHPMYADMIN_PORT:80"
    environment:
      <<: *default-tz-puid-pgid
      PMA_HOST: $MARIADB_HOST
      PMA_PORT: $MARIADB_PORT
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin-rtr.entrypoints=websecure"
      - "traefik.http.routers.phpmyadmin-rtr.rule=Host(`pma2.$DOMAINNAME`)"
      - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.phpmyadmin-rtr.service=phpmyadmin-svc"
      - "traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80"