services:
#Plex Image Cleanup
  plexic:
    <<: *common-keys-apps
    image: meisnate12/plex-image-cleanup
    container_name: plexic
    profiles: ["media", "all"]
    depends_on:
      - plex
    environment:
      <<: *default-tz-puid-pgid
      PLEX_PATH: /plex
      MODE: remove
      SCHEDULE: "07:00|weekly(sunday)"
      PLEX_URL: http://$SERVER_IP:$PLEX_PORT
      PLEX_TOKEN: /run/secrets/plex_token
      #DISCORD=https://discord.com/api/webhooks/###################/####################################################################
      TIMEOUT: 600
      SLEEP: 60
      IGNORE_RUNNING: True
      LOCAL_DB: False
      USE_EXISTING: False
      PHOTO_TRANSCODER: False
      EMPTY_TRASH: True
      CLEAN_BUNDLES: True
      OPTIMIZE_DB: True
      TRACE: False
      LOG_REQUESTS: True
    secrets:
      - plex_token
    volumes:
      - $DOCKERDIR/plex-image-cleanup/config:/config
      - $DOCKERDIR/Plex/DB/Library/Application Support/Plex Media Server:/plex