services:
  threadfin:
    image: fyb3roptik/threadfin
    container_name: threadfin
    ports:
      - 34400:34400
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/threadfin/conf:/home/threadfin/conf
      - $USERDIR//media/threadfin/temp:/tmp/threadfin:rw
    restart: unless-stopped