services:
# HomeAssistant - Smart Home Hub
 homeassistant:
   <<: *common-keys-apps
   image: homeassistant/home-assistant
   container_name: homeassistant
   profiles: ["infra", "all"]
#    ports:
#     - "$HASS_PORT:8123"
   tty: true
   volumes:
     - $DOCKERDIR/homeassistant:/config
     - /etc/localtime:/etc/localtime:ro
     - $DOCKERDIR/shared:/shared
   environment:
     <<: *default-tz-puid-pgid
   labels:
     - "traefik.enable=true"
     - "traefik.http.routers.homeassistant-rtr.entrypoints=https"
     - "traefik.http.routers.homeassistant-rtr.rule=Host(`hass.$DOMAINNAME`)"
     - "traefik.http.routers.homeassistant-rtr.middlewares=chain-no-auth@file"
     - "traefik.http.routers.homeassistant-rtr.service=homeassistant-svc"
     - "traefik.http.services.homeassistant-svc.loadbalancer.server.port=8123"