services:
# Lidarr - Music Management
  lidarr:
    <<: *common-keys-apps
    image: linuxserver/lidarr
    container_name: lidarr
    profiles: ["media", "all"]
#    ports:
#      - "$LIDARR_PORT:8686"
    volumes:
      - $DOCKERDIR/lidarr:/config
      - $DOWNLOAD_DIR:/downloads
      - $USERDIR/media/music:/music
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
    labels:
      - "traefik.enable=true"
      # HTTP Routers Auth Bypass
      - "traefik.http.routers.lidarr-rtr-bypass.entrypoints=websecure"
      - "traefik.http.routers.lidarr-rtr-bypass.rule=Host(`lidarr.$DOMAINNAME`) && (Header(`X-Api-Key`, `$LIDARR_API`) || Query(`apikey`, `$LIDARR_API`))"
      - "traefik.http.routers.lidarr-rtr-bypass.priority=100"
      # HTTP Routers Auth
      - "traefik.http.routers.lidarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.lidarr-rtr.rule=Host(`lidarr.$DOMAINNAME`)"
      - "traefik.http.routers.lidarr-rtr.priority=99"
      # Middlewares
      - "traefik.http.routers.lidarr-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.lidarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.lidarr-rtr.service=lidarr-svc"
      - "traefik.http.routers.lidarr-rtr-bypass.service=lidarr-svc"
      - "traefik.http.services.lidarr-svc.loadbalancer.server.port=8686"