services:
# LMS - Music Server
  lms:
    <<: *common-keys-apps
    image: lmscommunity/logitechmediaserver:8.5.3
#     image: reddthebamf/lms:8.4.0
    container_name: lms
    profiles: ["media", "all"]
    ports:
      - "$LMS_PORT1:9000"
      - "$LMS_PORT2:9090"
      - "$LMS_PORT3:3483"
      - "$LMS_PORT3:3483/udp"
    volumes:
      - $USERDIR/media/music:/srv/music:ro
      - $DOCKERDIR/squeezebox:/srv/squeezebox
      - /etc/localtime:/etc/localtime:ro
    environment:
      <<: *default-tz-puid-pgid
      JAVA_OPTS: -Dserver.use-forward-headers=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lms-rtr.entrypoints=websecure"
      - "traefik.http.routers.lms-rtr.rule=Host(`lms.$DOMAINNAME`)"
      - "traefik.http.routers.lms-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.lms-rtr.service=lms-svc"
      - "traefik.http.services.lms-svc.loadbalancer.server.port=9000"