services:
# Mosquitto - MQTT Broker
# Create mosquitto.conf, passwd, mosquitto.log files  and set permissions to 775 user:docker
# dexec mosquitto /bin/sh -> mosquitto_passwd -b /mosquitto/config/passwd username passwd
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["infra", "all"]
#    ports:
#      - "$MOSQUITTO_HTTP_PORT:1883" #http
#      - "9001:9001" #websockets
#      - "$MOSQUITTO_HTTPS_PORT:8883" #https 
    volumes:
      - $DOCKERDIR/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - $DOCKERDIR/mosquitto/data:/mosquitto/data
      - $DOCKERDIR/mosquitto/config/passwd:/mosquitto/config/passwd
      - $DOCKERDIR/shared:/shared
    environment:
      <<: *default-tz-puid-pgid