services:
# Traefik Certs Dumper - Extract LetsEncrypt Certificates - Traefik2 Compatible
  certdumper:
    <<: *common-keys-apps
    image: humenius/traefik-certs-dumper #kereis/traefik-certs-dumper:multi-arch-builds-alpine
    container_name: traefik_certdumper
    profiles: ["infra", "all"]
#    command: --restart-containers container1,container2,container3
    volumes:
      - $DOCKERDIR/traefik/acme:/traefik:ro
      - $DOCKERDIR/shared/certs:/output:rw
#    - /var/run/docker.sock:/var/run/docker.sock:ro # only needed if restarting containers
    environment:
      <<: *default-tz-puid-pgid
      DOMAIN: $DOMAINNAME