services:
# Pi-Hole DNS
  pihole:
    <<: *common-keys-core
    image: pihole/pihole
    container_name: pihole
    profiles: ["infra", "all"]
#      cap_add:
  #      - NET_ADMIN
    hostname: pihole
    networks:
      t3_proxy:
        ipv4_address: $PIHOLE_IP
#      dns:
#        - 127.0.0.1
#        - 1.1.1.1
    ports:
      - "$PIHOLE_PORT1:80"
      - "$PIHOLE_PORT2:443"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - $DOCKERDIR/pihole/resolv.conf:/etc/resolv.conf
      - $DOCKERDIR/pihole/pihole:/etc/pihole
      - $DOCKERDIR/pihole/dnsmasq.d:/etc/dnsmasq.d
      - $DOCKERDIR/pihole/logs/pihole.log:/var/log/pihole.log
    environment:
      <<: *default-tz-puid-pgid
      FTLCONF_REPLY_ADDR4: $SERVER_IP
#      VIRTUAL_HOST: pihole.$DOMAINNAME
      VIRTUAL_PORT: 80
      WEBPASSWORD: $PIHOLE_PASSWORD
      PIHOLE_DNS_: $ROUTER_IP
      DNS_BOGUS_PRIV: "true"
      REV_SERVER: "true"
      REV_SERVER_DOMAIN: $LOCALDOMAINNAME
      REV_SERVER_TARGET: $ROUTER_IP
      REV_SERVER_CIDR: $LOCAL_NETWORK
      ADMIN_EMAIL:  $MY_EMAIL
      WEBTHEME: "default-dark"
      RATE_LIMIT: 5000/60
   labels:
     - "traefik.enable=true"
     - "traefik.http.routers.pihole.rule=Host(`pihole2.${DOMAINNAME}`)"
     - "traefik.http.routers.pihole.entrypoints=websecure"
     - "traefik.http.services.pihole.loadbalancer.server.port=80"
     - "traefik.http.routers.pihole-rtr.middlewares=chain-oauth@file"