services:
# Glances - System Information
  glances:
    <<: *common-keys-apps
    image: nicolargo/glances:latest-full
    container_name: glances
    profiles: ["infra", "all"]
#    privileged: true
    networks:
      - t3_proxy
      - socket_proxy
      - default    
    ports:
      - "$GLANCES_PORT:61208"
    pid: host
    volumes:
      - $DOCKERDIR/glances/glances.conf:/glances/conf/glances.conf # Use this if you want to add a glances.conf file
#      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $USERDIR/media:/media:ro
    environment:
      <<: *default-tz-puid-pgid
#      GLANCES_OPT: "-C /glances/conf/glances.conf --quiet --export influxdb"
      GLANCES_OPT: "-w --password"
      DOCKER_HOST: tcp://socket-proxy:2375
    secrets:
      - source: glances_password
        target: /root/.config/glances/glances.pwd
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glances-rtr.entrypoints=websecure"
      - "traefik.http.routers.glances-rtr.rule=Host(`glances.$DOMAINNAME`)"
      - "traefik.http.routers.glances-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.glances-rtr.service=glances-svc"
      - "traefik.http.services.glances-svc.loadbalancer.server.port=61208"