services:
# Gluetun - VPN Client for Docker Containers and More
# Gluetun only for use by torrent clients + on demand lan devices.
# Arr apps do not need VPN (not recommended), unless you have ISP/country restrictions.
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["infra", "all"]
    networks:
      - t3_proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "8081:8080" # Exposing qBittorrent through Docker Host LAN IP
      - "31801:31801"
    # #   - 8888:8888/tcp # HTTP proxy
    # #   - 8388:8388/tcp # Shadowsocks
    # #   - 8388:8388/udp # Shadowsocks
    volumes:
      - $DOCKERDIR/gluetun:/gluetun
    environment:
      TZ: $TZ
      # Wireguard
      # VPN_SERVICE_PROVIDER: surfshark
      # VPN_TYPE: wireguard
      # WIREGUARD_PRIVATE_KEY: $SURFSHARK_WG_PRIVATE_KEY
      # WIREGUARD_ADDRESSES: 10.14.0.2/16
      # SERVER_COUNTRIES: Netherlands
      # OpenVPN
      VPN_SERVICE_PROVIDER: private internet access
      VPN_TYPE: openvpn
      PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING: on
      PRIVATE_INTERNET_ACCESS_VPN_PRIVATE_INTERNET_ACCESS_VPN_PORT_FORWARDING_STATUS_FILE: /gluetun/forwarded_port
      VPN_PORT_FORWARDING_USERNAME_SECRETFILE: /run/secrets/openvpn_user
      VPN_PORT_FORWARDING_PASSWORD_SECRETFILE: /run/secrets/openvpn_password
      OPENVPN_CONFIG: "US Dallas"
      OPENVPN_OPTS: --inactive 3600 --ping 10 --ping-exit 60
    secrets:
      - source: pia_username
        target: /run/secrets/openvpn_user
      - source: pia_password
        target: /run/secrets/openvpn_password
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.gluetun-qbittorrent-rtr.entrypoints=websecure"
      - "traefik.http.routers.gluetun-qbittorrent-rtr.rule=Host(`qbit.$DOMAINNAME`)" # qBittorrent
      # Middlewares
      - "traefik.http.routers.gluetun-qbittorrent-rtr.middlewares=chain-oauth@file" # qBittorrent
      # HTTP Services
      - "traefik.http.routers.gluetun-qbittorrent-rtr.service=gluetun-svc" # qBittorrent
      - "traefik.http.services.gluetun-svc.loadbalancer.server.port=8080" # qBittorrent