services:
# MKVcleaver is a GUI (Graphical User Interface) for mkvtoolnix, designed to extract data from MKV files.
  mkvcleaver:
    <<: *common-keys-apps
    image: jlesage/mkvcleaver
    container_name: mkvcleaver
    profiles: ["avedit"]
#    ports:
#      - "$MKVCLEAVER_PORT:5800"
    volumes:
      - $USERDIR/media:/media:rw
      - $DOWNLOAD_DIR:/downloads:rw
      - $DOCKERDIR/mkvcleaver/config:/config:rw
      - $USERDIR/media/storage:/base_storage:rw
    environment:
      <<: *default-tz-puid-pgid
      UMASK: 002
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 960
      DARK_MODE: 1
    devices:
      - /dev/dri:/dev/dri
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mkvcleaver-rtr.entrypoints=https"
      - "traefik.http.routers.mkvcleaver-rtr.rule=Host(`mkvcleaver.$DOMAINNAME`)"
      - "traefik.http.routers.mkvcleaver-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.mkvcleaver-rtr.service=mkvcleaver-svc"
      - "traefik.http.services.mkvcleaver-svc.loadbalancer.server.port=5800"